# Generated by Django 3.0.4 on 2020-03-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_data_app', '0003_auto_20200318_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='legal_form',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
